FORMAT: 1A

# Template

## Version [/version]

### GET 

+ Response 200 (application/json)

    + Body

            {
                {
                    "version": "1.0.0-SNAPSHOT",
                    "name": "template"
                }
            }


## Images [/{width}/{height}/{key}.{ext}]

+ parameters
    + width: 1020 (required, integer) - requested width for the Images 
    + height: 780 (required, integer) - requested height for the Images 
    + key: users/ha998 (required, string) - key of the image stored in the s3 bucket
    + ext: jpeg (required, string) - desired extension for the image


### GET

+ Response 200 (image/jpeg)